[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://inventory-management-sbm.up.railway.app/api/:splat"
  status = 200
